baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

# Use highlight.js for syntax highlighting
# https://github.com/dzello/reveal-hugo#syntax-highlighting
[markup.highlight]
codeFences = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.logo]
src = "images/hs-worms-logo.png"
diag = "5%"
width = "10%"

[params.reveal_hugo]
theme = "white"
# https://github.com/dzello/reveal-hugo/issues/58
custom_css = "css/custom.css"
highlight_theme = "github"
transition = "zoom"
